### PR TITLE
Modify Dockerfile for Linux

### PR DESCRIPTION
**Pull request by nayuta723**
## Modified part
Remove options ```-platform``` and change `postgres:15` into `postgres:latest`.

### CODE REVIEW

**Comment by Rwatana** [comment]
I was successful in the build. Here are the results.

I was stumped by the creation of the container.
It gave me an error that there was no go.mod file.
However, the file has been created.
What does this mean?

I updated the file. Please give me an advice.
```
ryoma@gorgon:~/Okudaseminar/course_kuburnetess/Assignment3$ docker-compose build
Building postgres
Sending build context to Docker daemon  18.43kB
Step 1/6 : FROM   postgres:latest
latest: Pulling from library/postgres
a603fa5e3b41: Pull complete 
02d7a77348fd: Pull complete 
16b62ca80c8f: Pull complete 
fbd795da1fe1: Pull complete 
9c68de39d930: Pull complete 
2e441a95082c: Pull complete 
1c97f440fe14: Pull complete 
87a3f78bc5d1: Pull complete 
264b18cba666: Pull complete 
bea1513c492d: Pull complete 
ed48cace97fa: Pull complete 
e3c377e275ff: Pull complete 
86fa351e30cb: Pull complete 
Digest: sha256:766e8867182b474f02e48c7b1a556d12ddfa246138ddc748d70c891bf2873d82
Status: Downloaded newer image for postgres:latest
 ---> 68f5d950dcd3
Step 2/6 : ENV LC_ALL en_US.UTF-8
 ---> Running in 9e3ef1f4ae77
Removing intermediate container 9e3ef1f4ae77
 ---> 6bae8de231d4
Step 3/6 : ENV LC_CTYPE en_US.UTF-8
 ---> Running in 20516ab2bbd9
Removing intermediate container 20516ab2bbd9
 ---> 63fa4223e219
Step 4/6 : RUN localedef -i ja_JP -c -f UTF-8 -A /usr/share/locale/locale.alias ja_JP.UTF-8
 ---> Running in db7eed97d986
Removing intermediate container db7eed97d986
 ---> bef40369549f
Step 5/6 : ENV LANG ja_JP.UTF-
 ---> Running in 4888a7ec4542
Removing intermediate container 4888a7ec4542
 ---> 18a778878f0c
Step 6/6 : COPY ./docker/postgres/init/*.sql /docker-entrypoint-initdb.d/
 ---> caa831d103af
Successfully built caa831d103af
Successfully tagged assignment3_postgres:latest
Building app
Sending build context to Docker daemon  18.43kB
Step 1/6 : FROM golang:1.19
1.19: Pulling from library/golang
a8ca11554fce: Pull complete 
e4e46864aba2: Pull complete 
c85a0be79bfb: Pull complete 
195ea6a58ca8: Pull complete 
52908dc1c386: Pull complete 
a2b47720d601: Pull complete 
14a70245b07c: Pull complete 
Digest: sha256:dc76ef03e54c34a00dcdca81e55c242d24b34d231637776c4bb5c1a8e8514253
Status: Downloaded newer image for golang:1.19
 ---> 8ee516e10ce0
Step 2/6 : WORKDIR /go/src/github.com/postgres-go
 ---> Running in dde8fdda6e0c
Removing intermediate container dde8fdda6e0c
 ---> fb83808f465b
Step 3/6 : COPY . .
 ---> b96158bc1eb1
Step 4/6 : RUN go mod download && go mod verify
 ---> Running in 2bc24e08f1c2
all modules verified
Removing intermediate container 2bc24e08f1c2
 ---> 0f010875cd3e
Step 5/6 : WORKDIR /usr/ryoma/go
 ---> Running in 3668e48ae36e
Removing intermediate container 3668e48ae36e
 ---> 167971383252
Step 6/6 : ADD ./go .
 ---> a42166c0055e
Successfully built a42166c0055e
Successfully tagged assignment3_app:latest
```

```
ryoma@gorgon:~/Okudaseminar/course_kuburnetess/Assignment3$ docker-compose up
Starting postgres ... done
Starting app      ... done
Attaching to postgres, app
postgres    | 
postgres    | PostgreSQL Database directory appears to contain a database; Skipping initialization
postgres    | 
postgres    | 2022-12-01 08:46:39.104 UTC [1] LOG:  starting PostgreSQL 15.1 (Debian 15.1-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
postgres    | 2022-12-01 08:46:39.104 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgres    | 2022-12-01 08:46:39.104 UTC [1] LOG:  listening on IPv6 address "::", port 5432
postgres    | 2022-12-01 08:46:39.113 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres    | 2022-12-01 08:46:39.140 UTC [28] LOG:  database system was shut down at 2022-12-01 08:46:35 UTC
postgres    | 2022-12-01 08:46:39.149 UTC [1] LOG:  database system is ready to accept connections
app         | main.go:10:2: no required module provides package github.com/lib/pq: go.mod file not found in current directory or any parent directory; see 'go help modules'
app exited with code 1
```

**Comment by nayuta723** [comment]
This will work. The above error is caused by missing the go.mod file position. So, I changed the location of go.mod file.

**Comment by nayuta723** [comment]
As you can see in the error, go.mod does not exist above the current directory.
```app         | main.go:10:2: no required module provides package github.com/lib/pq: go.mod file not found in current directory or any parent directory; see 'go help modules'```

**Comment by Rwatana** [comment]
## Topic
In my point of view, I couldn't see the change. 

スクリーンショット 2022-12-01 19 49 34

So, I change the file according to your record of your change in this pull request.
I updated the file. Please check.
The place of go.mod file seems that there are no change. 
Could you tell me the way of confirming the place of that file.

**Comment by ryuji0123** [comment]
@Rwatana 
I think you should check your directory structure first. Why did you change it from the original one?
https://github.com/okuda-seminar/document_links/tree/main/course_kubernetes/Assignment3

**Comment by Rwatana** [comment]
@ryuji0123 
A comparison of the two, I am assuming you are asking why the go.mod file exists correct?

First, I get an error that shows do run go get -u [github.com/lib/pq](https://github.com/lib/pq) 
Simply doing that doesn't work, so I did a go mod init to get the command to work.
I fixed this error during that process, so the file is still there now.

**Comment by ryuji0123** [comment]
@nayuta-ai 
Can you update the doc and clearly show each step like [DB](https://github.com/okuda-seminar/document_links/tree/main/course_database/Assignment3)?
I think sth is misunderstood. Also, why doesn't [this](https://github.com/okuda-seminar/document_links/tree/main/course_kubernetes/Assignment3#step0-install-golang) use Docker?

**Comment by nayuta723** [comment]
@Rwatana 
Please check the PR, as it has been changed within the PR. （Not merged into main.）
@ryuji0123 
OK, I will update it like DB until tomorrow.
Because installing Golang is necessary for building a Golang environment on Docker, such as creating `go.mod` file, reflecting `GOPATH` to environment variables in Docker, and so on, all article I have checked uses Golang on the local environment.

**Pull request merged**
